### ISSUE TITLE
Networking Infrastructure

### ISSUE THREAD

**Issue by camden-bock** [maine-imre/handwaver#15]
**Is your feature request related to a problem? Please describe.**
We currently allow for multiple players in the same space, but we want to be able to align networked space that exists in the same physical space.  We also need to support voice and hands better for users that do not share a physical space. 

**Describe the solution you'd like**
We need a solution using PUN that represents avatars in a way that is usable in shared and unshared physical spaces.  We also need a simple mechanism to create public and private rooms and to enter those rooms.

As we implement these, we should consider what parts of this support could help develop a way to replay a user's experience in the environment.

**Describe alternatives you've considered**
We've tried a Unity UNet implication before, but PUN 2 seems to be much easier to work with.  Unity is coming out with new network support that we will consider in the future.

**Additional context**
There are two scenes for initial networking support.

- [x] HyperBall
  - [x] Optimization
- [ ] Dimension Study
   - [ ] Initalize Stage RPC
   - [ ] Advance Stage RPC
   - [ ] Adjust Slider RPC

***Basic Infrastructure***
- [x] Network Hands
- [ ] Network Voice - should have a clear toggle.
- [ ] Simple, string-based room selection.  Basically, we pre-build the scene that you are entering, and that becomes the prefix on the room name (or it could be the version number?).  Then when the program starts, you have two options on the desktop (a) create new room and (b) join room (c)  join random room.  In the case of (a) we randomize a string of unambiguous characters and assign that as the room name.  In the case of (b) you type in the string and the system searches for that room.  Finally, we need to have a lab-specific prefix.  That is, for research, we have a prefix (IMRE) that is not allowed in joining a random room.  We could also do this by setting IMRE as a prefix on the version number so there would be a version mismatch for anyone trying to join a research study from outside.
- [ ] Better way for naming users.  Randomly generate names pulling a color, adjective, and noun from a list?

***Improve Avatars*** - basically, we want to have something that is representative enough to be workable but doesn't attract attention.

This part of the work would be a good first task for someone when @nsgnn figures out the stuff above.
- [x] Blocks for Hands
- [x] Blocks for head and body
- [x] blocks for controllers
- [ ] some sort of block-based hand model

**Comment by cam3715** [comment]
Our current implementation needs to be optimized, it is too choppy on the client machine.
Consider execution order.
Consider 

Learning from this, when we integrate with the Geometry Kernel, we should consider running separate threads on the server and an event-based update system.

**Comment by cam3715** [comment]
Consider Discord Rich Presence for room selection

**Comment by cam3715** [comment]
As a modification for schools, we could allow for a room code in the launcher.  A teacher might use their name combined with their school's name.  If application is launched without a room code, it would join a random public room

**Comment by cam3715** [comment]
Consider using discord integration to resolve voice networking.  Less of an issue for schools if they are sharing space

**Comment by camden-bock** [comment]
We will no longer be supporting networking for the scale and dimension study.

Use of the discord API for voice sharing will be addressed in another issue.
