### ISSUE TITLE
Remove Closed Source Dependencies, except for PUN.

### ISSUE THREAD

**Issue by camden-bock** [maine-imre/handwaver#32]
**Is your feature request related to a problem? Please describe.**
We want to limit the closed source dependencies in our project (and eventually eliminate).

**Describe the solution you'd like**
- [x] Remove dependency on Pool manager.
- [x] Make build target flags to allow to compile without other optional closed source.
- [x] Add linux support (editor)

**Comment by cam3715** [comment]
Build target flags used for MixCast.
@Joey-Haney we need to know more about the Davinci video workflow to see if we can depreciate MixCast.  One possibility for doing this is to have a MixCast scene that gets loaded on top.  The MixCast asset could then be added if someone wanted it.  We only want to make this move if we are going to be able to work without MixCast in our research data collection.

**Comment by cam3715** [comment]
A new script has been written to replace the PoolManager.  We need to test the performance on this.

**Comment by cam3715** [comment]
@nsgnn any ideas on what to do with the OnSpawned calls?  Just change to OnStart?  some other mechanism?

**Comment by cam3715** [comment]
@Joey-Haney @nsgnn Ideally we test this and merge it into develop - then update other feature branches - before starting new work (e.g. more networking or more gesture work).

**Comment by cam3715** [comment]
As I consider this further, we are going to need to do something about how we use build targets for MixCast.

We should consider having both MixCast and Windows flags on for those build targets, and accept the inconvenience in the editor.  This would fit better with the put MixCast and other closed assets in Forks only philosophy.

**Comment by cam3715** [comment]
Problems with prefabs.  Instead of using prefabs and pooling for GeoObjs, we will have a constructor script for each GeoObj.

**Comment by nsgnn** [comment]
completed
