### ISSUE TITLE
Move Stretch to be a gesture in the gesture system.

### ISSUE THREAD

**Issue by camden-bock** [maine-imre/handwaver#60]

**Comment by cam3715** [comment]
The conditions would be similar to the Double Pinch no grasp, except that it would specifically require grasping.

**Comment by cam3715** [comment]
This is currenlty implemented by watching for multihandgrasp

**Comment by cam3715** [comment]
This move would help us prepare for an ECS system.

**Comment by cam3715** [comment]
Turns out that we need this desperately.

**Comment by Joey-Haney** [comment]
Duplicate of #14
