### ISSUE TITLE
Rebuild menu in RSDES

### ISSUE THREAD

**Issue by camden-bock** [maine-imre/handwaver#62]
The prefab doesn't work

Maybe this is a good time to consider a different design?

**Comment by cam3715** [comment]
This is needed for the PushPins and for the Global menu

**Comment by nsgnn** [comment]
@camden-bock @Joey-Haney Could this be closed as wont-do if we are swapping to the new embodied user input system for rsdes?

**Comment by camden-bock** [comment]
@nsgnn this issue is now closed.
